### PR TITLE
Source - added function for getting all features of the source (getFeatures())

### PR DESCRIPTION
**Pull request by mazlixek**
ViewOptions - added methods for limiting zoom levels (setMaxZoom,
setMinZoom)

### CODE REVIEW

**Comment by TDesjardins** [comment]
Hello @mazlixek ,

thanks for your contribution. The abstract class Source has no getFeatures method because not all sources have features e.g. Image. You can find the method in Vector source and it is already available in gwt-ol3. The other commit is fine. Could you change the pull request?

**Comment by mazlixek** [comment]
Ok I removed the getFeatures() from Source. Ty for information about the VectorSource.

**Comment by TDesjardins** [comment]
Could you please remove the unnecessary change in Source?

**Comment by mazlixek** [comment]
I guess I finally managed to do it correctly :D sorry my first pull request.

**Comment by TDesjardins** [comment]
No problem! Thanks!

**Pull request merged**
