### PR TITLE
Fix for OLUtil.observe and OLUtil.observeOnce

### PR DESCRIPTION
**Pull request by sebasbaumh**
Fix for `OLUtil.observe` and `OLUtil.observeOnce` to prevent error with missing function `onEvent` in event handler.
Version bump.

### CODE REVIEW

**Comment by TDesjardins** [comment]
In which cases do you get an error? Could it be that you doesn't use flag -generateJsInteropExports?

**Comment by sebasbaumh** [comment]
I used the flag, but there still seem to be issues with methods in generic classes, which get renamed by GWT.
In JavaScript the generated code looks like two (renamed) functions, where one does the type checking and calls the second one. But both do not retain the original name.
The workaround was to create a non-generic function in between, which does just cast to the generic type (which is checked by GWT anyway).
Looking at the generated JavaScript for this function shows that it actually retains the name after compilation - which is why it works.

I think we had a bug like that before with generic classes, but I do not remember the details :-/

**Comment by TDesjardins** [comment]
I think there is a better way to get this things done. Less code, simpler usage and without the need of JsExports. We only have to use JsInterop features. I propose that I will make a commit with this change and then you could test if it solve your issues. Is this ok for you?
Further I want to reduce the methods in OLUtils in future which belong to instance classes to better find them and reduce dependencies.

**Comment by sebasbaumh** [comment]
Yes, I would be happy to check that. It took quite some time to track it down, but now I know what to look at ;-)

**Comment by TDesjardins** [comment]
Done! Could you test this?

**Comment by sebasbaumh** [comment]
I just tested your implementation and it works for me :-)
The strange thing is that I tried something similar using `JsFunction` before, maybe I just missed out a thing on that.

Could you please still do a version bump so that I can package the fix into a new version?
I would then close this pull request as it makes no more sense.

**Comment by TDesjardins** [comment]
Because there are some new stuff I set the version to 2.8.0. I am a little bit careless with versioning. That must be get better in future ;-)

**Comment by sebasbaumh** [comment]
Perfect :-)
Yes, that will really help.

**Pull request closed without merging**
