### PR TITLE
Completion of  textoption and SrokeOption

### PR DESCRIPTION
**Pull request by AAauAAau**

### CODE REVIEW

**Comment by TDesjardins** [comment]
Hello AAau...,

thank you for contribution. I have some small remarks. First there is a bug in TextOptions:

See: https://github.com/TDesjardins/gwt-ol3/pull/25/commits/a790081126306bd5200935383e79ed550e7133c1#diff-074653f31ffb3625bf219f2ec6aa937fR62

Second could you please remove commit 89f9231 (no message)? Because if you use wildcards in imports it is hard to see dependencies at a glance.

Regards

Tino

**Comment by TDesjardins** [comment]
Thanks!

**Comment by AAauAAau** [comment]
Thanks, sorry for the Bugs

2016-04-25 12:48 GMT+02:00 TDesjardins <notifications@github.com>:

**Comment by TDesjardins** [comment]
Hey @AAauAAau ,

no problem! Now it should work.

Regards

Tino

**Pull request merged**
