### PR TITLE
lobmarib gwt2.8 improvements

### PR DESCRIPTION
**Pull request by lobmarib**
Finally I could create the correct pull request.

Please feel free to comment

### CODE REVIEW

**Comment by TDesjardins** [comment]
Hello Marco,

thanks for your contributions. One pull request with changes in 31 files is hard to merge. So please make pullrequests per feature next time.

Before I can merge this you have to remove your copyright entries in the classfile header because the project is licensed under the Apache License, Version 2.0. You can put the autor and the date in the class header.

You can remove the JSProperty names if they follow getter / setter syntax.

Regards

Tino

**Comment by lobmarib** [comment]
Hi Tino,

I did those changes to fulfill my needs in a project and then I decided to share them, that's why I have so many changes in just one go... Sorry about that. Next time I will do it by feature.

Yes, I just forgot to select the correct file headers.

Going to do that changes in a moment.

Regards
Marco

**Comment by TDesjardins** [comment]
Hello Marco,

no problem! Let me know if I can help you.

Regards

Tino

**Comment by TDesjardins** [comment]
Thanks!

**Pull request merged**
