### PR TITLE
Add text placement

### PR DESCRIPTION
**Pull request by ikzent**
The actual style and text does not support the placement of text along a feature line, an additional setter was added

### CODE REVIEW

**Comment by TDesjardins** [comment]
Hello @ikzent ,
seems that your branch is dirty. Please reset and rebase or simply create a fresh fork!

**Comment by ikzent** [comment]
I reapplied the changes, the result is better next time when adding functionality I will check these first

**Comment by TDesjardins** [comment]
Ok, thanks! Could you exclude the format changes in VectorOptions? After this I will merge.

**Comment by ikzent** [comment]
Done

**Comment by TDesjardins** [comment]
Thanks!

**Pull request merged**
