### PR TITLE
Wrapper for ol.source.Raster and ol.RasterOperation

### PR DESCRIPTION
**Pull request by d-eggert**
Hi Tino,

i implemented the wrapper classes and interfaces as pointed out in my issue #128. 
After further study, i identified the mapping for the pixel arrays and added an additional `PixelColor` class extending `JsArrayLike`.

I also added a corresponding example for the showcase. Yet the example fails with an `Uncaught SyntaxError: Unexpected number` error, when selected. Maybe you can take a look at it?

-- Daniel

### CODE REVIEW

**Comment by TDesjardins** [comment]
Hello Daniel,

I think this is a good starting point. After some modifications of your code the example works. I will switch the source to OSM because the choosen image doesn't provide a cross origin response header. Otherwise you will run into a cross origin problem.
There are still some problems to solve for a productive solution. I will take a look on this.

**Comment by TDesjardins** [comment]
Hello Daniel,

could you give me write access to this pull request (See [allow editing](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) )? Then I could add my changes to get the example working.

**Comment by d-eggert** [comment]
Hi Tino,

the allow edits box is already checked, so you should be able to commit your changes.

-- Daniel

**Comment by TDesjardins** [comment]
Alright. You could now check the changes and test the example. This is only a preliminary step and there are some open issues:

- image raster operation type support
- support of workers (num of threads and lib)

**Comment by d-eggert** [comment]
I checked the changes and tested the example. Looks good so far. 

Regarding the image type support, there is actually not much to do. The js ImageData object translates just fine to the JsArrayLike PixelColor class, containing all pixels for the entire image instead of a single pixel. We could provide an appropriate class with some convenience methods to support basic image wide operations. I will make a suggestion later on.

The worker support is far more interesting. As far as I can see, the example only works if the use of worker threads is disabled. As soon as we set the number of worker threads to a value other than 0, an `Uncaught ReferenceError: samMethod_0_g$ is not defined` is thrown.
As soon as I set the Lib option parameter the compiler kind of produces invalid javascript code, resulting in `Uncaught SyntaxError: Unexpected number` errors. Since I'm no JavaScript developer, being the reason for using gwt in the first place :eyes:, I'm not sure where to start looking for the root of this problem. Maybe you could point me to the right direction.

**Comment by d-eggert** [comment]
I played a little bit around with the example and found the generic user data parameter super annoying. From a Java perspective it's kind of redundant anyway, since you can reference almost anything you want from within your interface implementation stub. So I removed the userdata parameter from the RasterOperation function, making all involved classes it a lot cleaner.

I also provided an image raster operation type example, based on the `com.google.gwt.canvas.dom.client.ImageData` class. The operation is more or less arbitrary but as an example it should be sufficient.

**Comment by TDesjardins** [comment]
This isn't a question of Java or not Java. In both languages you can use "closures". The reason for the need of the user data object is the access of the data inside a worker. This is also true for the lib object. This object is only for storing functions that need to be executed in workers threads. Since the workers feature currenly doesn't work, you don't need these parameters at this time. If we want to support workers, these properties are needed if you want to access functions and data inside workers.
Supporting this workers feature with JsInterop seems complicated, maybe it isn't possible. It's time for some investigations to check the possibilty.
`samMethod_0_g$` is a JsInterop encapsulation of the "functional interface implementation" of RasterOperation. This is not known in the worker thread.

You should replace `com.google.gwt.canvas.dom.client.ImageData` to `elemental2.dom.ImageData` because the elemental stuff is compatible with JsInterop.

I suggest to make this pull request work with basic raster source support without worker properties. After that I could merge it and we can then add additional functionality.

**Comment by d-eggert** [comment]
I replaced the gwt `ImageData` class with `elemental2.dom.ImageData`. Since the elemental version lacks pixel value getter and setter, I extended the class in 'ol.ImageData' providing the said getter and setter.

So, whats your suggestion regarding the userdata parameter? 
I see two options here:
1. We omit it as in my current version and re-add it later in case we get the web worker stuff working
or
2. We keep it, though we don't really need it, so we don't have to change the api later on for the said web worker stuff

Since we are going to omit the worker support, shall we make sure that the threads are automatically set to `0`? Or just document it, that it has to be done in order work. 
I would prefer the former one. As far as I can tell, we would need to provide a separate factory method for this, which somehow contradicts your generic one. Do you have another suggestion for this?

**Comment by TDesjardins** [comment]
I am for hiding the worker support till it will work.
Please do not mix format changes with functional changes in pull requests! I will not merge before you revert/undo format changes in existing code (OLFactory).

**Comment by d-eggert** [comment]
Sorry for the format change, i forgot that the auto-format on save is enabled in my ide. I reverted the unintended format changes.

Are we good to merge?

**Comment by TDesjardins** [comment]
@d-eggert No problem 😉 ! The project needs some contribution guidelines to help contributors.
Thanks, looks good so far. I will give it a short test and then merge.

**Comment by TDesjardins** [comment]
Well done! Your example is very nice. Thanks for your efforts!

**Pull request merged**
