### PR TITLE
Add some missing StyleFunction

### PR DESCRIPTION
**Pull request by Fractaliste**
Following your work at https://github.com/TDesjardins/gwt-ol3/issues/137

### CODE REVIEW

**Comment by TDesjardins** [comment]
Looks good. Thanks!

**Comment by Fractaliste** [comment]
I'm not really familiar with Github, is it possible to push directly (from my local git client) into your repo (on an other branch of course) instead of having to fork your project each time on Github?

I try following but I got a permission denied return:

```
git remote add tdesjardin https://github.com/TDesjardins/gwt-ol3.git
git push tdesjardin api-completion
=> remote: Permission to TDesjardins/gwt-ol3.git denied to Fractaliste.

```

**Comment by TDesjardins** [comment]
@Fractaliste You could ckeck: https://gist.github.com/ravibhure/a7e0918ff4937c9ea1c456698dcd58aa

**Comment by Fractaliste** [comment]
Thanks, I'll try next pull request!

**Pull request merged**
